### ISSUE TITLE
Error with PHLAT

### ISSUE THREAD

**Issue by malonzm1** [chrisamiller/docker-phlat#7]
Hi,

PHLAT works with some of my samples but with others it throws the following error:

Traceback (most recent call last):
  File "/scratch/cs/pan-autoimmune/utilities/phlat/phlat-release/dist/PHLAT.py", line 72, in <module>
    go(tag,outdir,phlatdir,rmdir=rmtmp)
  File "/root/phlat2/dist/utilities.py", line 79, in go
  File "/home/yu.bai/phlat-release/dist/extensions.py", line 622, in __init__
  File "/home/yu.bai/phlat-release/dist/extensions.py", line 652, in setMaster
IndexError: list index out of range

This occurs after Bowtie2 alignment. Please advise.

Thanks and good day.

**Comment by chrisamiller** [comment]
Sorry, I'm just an end user and didn't write phlat, but if you want to see how we're using it, then you can look at our WDL here:  https://github.com/wustl-oncology/analysis-wdls/blob/main/definitions/tools/phlat.wdl
